### ISSUE TITLE
Write the blog post

### ISSUE THREAD

**Issue by tpbowden** [sadir/git-pairing-session#5]
Your readme is a lie

**Comment by dazoakley** [comment]
![http://i0.kym-cdn.com/photos/images/facebook/000/115/357/portal-cake.jpg](http://i0.kym-cdn.com/photos/images/facebook/000/115/357/portal-cake.jpg)

**Comment by sadir** [comment]
Oh god you brought other people in here. I knew you couldn't be trusted.
